// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, group_id, is_admin)
VALUES ($1, $2, $3, $4)
RETURNING username, password_hash, id, created_at, updated_at, is_admin, group_id
`

type CreateUserParams struct {
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	GroupID      uuid.UUID `json:"group_id"`
	IsAdmin      bool      `json:"is_admin"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.GroupID,
		arg.IsAdmin,
	)
	var i User
	err := row.Scan(
		&i.Username,
		&i.PasswordHash,
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.GroupID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT username, password_hash, id, created_at, updated_at, is_admin, group_id FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.Username,
		&i.PasswordHash,
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.GroupID,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT username, password_hash, id, created_at, updated_at, is_admin, group_id FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.Username,
		&i.PasswordHash,
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.GroupID,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET password_hash = $2, group_id = $3, is_admin = $4, updated_at = now()
WHERE id = $1
RETURNING username, password_hash, id, created_at, updated_at, is_admin, group_id
`

type UpdateUserParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
	GroupID      uuid.UUID `json:"group_id"`
	IsAdmin      bool      `json:"is_admin"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.PasswordHash,
		arg.GroupID,
		arg.IsAdmin,
	)
	var i User
	err := row.Scan(
		&i.Username,
		&i.PasswordHash,
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.GroupID,
	)
	return i, err
}
