// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: annotations.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAnnotation = `-- name: CreateAnnotation :one
INSERT INTO annotations (
    video_id, timestamp_seconds, duration_seconds, position_x, position_y,
    region_x, region_y, region_width, region_height, shape, display_mode,
    interactive, content, kind, color, custom_data
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
RETURNING video_id, timestamp_seconds, content, kind, color, custom_data, id, created_at, updated_at, duration_seconds, position_x, position_y, region_x, region_y, region_width, region_height, shape, display_mode, interactive
`

type CreateAnnotationParams struct {
	VideoID          uuid.UUID `json:"video_id"`
	TimestampSeconds float64   `json:"timestamp_seconds"`
	DurationSeconds  float64   `json:"duration_seconds"`
	PositionX        *float64  `json:"position_x"`
	PositionY        *float64  `json:"position_y"`
	RegionX          *float64  `json:"region_x"`
	RegionY          *float64  `json:"region_y"`
	RegionWidth      *float64  `json:"region_width"`
	RegionHeight     *float64  `json:"region_height"`
	Shape            string    `json:"shape"`
	DisplayMode      string    `json:"display_mode"`
	Interactive      bool      `json:"interactive"`
	Content          []byte    `json:"content"`
	Kind             string    `json:"kind"`
	Color            string    `json:"color"`
	CustomData       []byte    `json:"custom_data"`
}

func (q *Queries) CreateAnnotation(ctx context.Context, arg CreateAnnotationParams) (Annotation, error) {
	row := q.db.QueryRow(ctx, createAnnotation,
		arg.VideoID,
		arg.TimestampSeconds,
		arg.DurationSeconds,
		arg.PositionX,
		arg.PositionY,
		arg.RegionX,
		arg.RegionY,
		arg.RegionWidth,
		arg.RegionHeight,
		arg.Shape,
		arg.DisplayMode,
		arg.Interactive,
		arg.Content,
		arg.Kind,
		arg.Color,
		arg.CustomData,
	)
	var i Annotation
	err := row.Scan(
		&i.VideoID,
		&i.TimestampSeconds,
		&i.Content,
		&i.Kind,
		&i.Color,
		&i.CustomData,
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DurationSeconds,
		&i.PositionX,
		&i.PositionY,
		&i.RegionX,
		&i.RegionY,
		&i.RegionWidth,
		&i.RegionHeight,
		&i.Shape,
		&i.DisplayMode,
		&i.Interactive,
	)
	return i, err
}

const createAnnotationComment = `-- name: CreateAnnotationComment :one
WITH inserted AS (
    INSERT INTO annotation_comments (annotation_id, user_id, body)
    VALUES ($1, $2, $3)
    RETURNING annotation_id, user_id, body, id, created_at, updated_at
)
SELECT inserted.annotation_id, inserted.user_id, inserted.body, inserted.id, inserted.created_at, inserted.updated_at, users.username AS author_username
FROM inserted
JOIN users ON users.id = inserted.user_id
`

type CreateAnnotationCommentParams struct {
	AnnotationID uuid.UUID `json:"annotation_id"`
	UserID       uuid.UUID `json:"user_id"`
	Body         string    `json:"body"`
}

type CreateAnnotationCommentRow struct {
	AnnotationID   uuid.UUID        `json:"annotation_id"`
	UserID         uuid.UUID        `json:"user_id"`
	Body           string           `json:"body"`
	ID             uuid.UUID        `json:"id"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	AuthorUsername string           `json:"author_username"`
}

func (q *Queries) CreateAnnotationComment(ctx context.Context, arg CreateAnnotationCommentParams) (CreateAnnotationCommentRow, error) {
	row := q.db.QueryRow(ctx, createAnnotationComment, arg.AnnotationID, arg.UserID, arg.Body)
	var i CreateAnnotationCommentRow
	err := row.Scan(
		&i.AnnotationID,
		&i.UserID,
		&i.Body,
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorUsername,
	)
	return i, err
}

const deleteAnnotation = `-- name: DeleteAnnotation :execrows
DELETE FROM annotations WHERE id = $1
`

func (q *Queries) DeleteAnnotation(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAnnotation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAnnotationByID = `-- name: GetAnnotationByID :one
SELECT video_id, timestamp_seconds, content, kind, color, custom_data, id, created_at, updated_at, duration_seconds, position_x, position_y, region_x, region_y, region_width, region_height, shape, display_mode, interactive FROM annotations WHERE id = $1
`

func (q *Queries) GetAnnotationByID(ctx context.Context, id uuid.UUID) (Annotation, error) {
	row := q.db.QueryRow(ctx, getAnnotationByID, id)
	var i Annotation
	err := row.Scan(
		&i.VideoID,
		&i.TimestampSeconds,
		&i.Content,
		&i.Kind,
		&i.Color,
		&i.CustomData,
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DurationSeconds,
		&i.PositionX,
		&i.PositionY,
		&i.RegionX,
		&i.RegionY,
		&i.RegionWidth,
		&i.RegionHeight,
		&i.Shape,
		&i.DisplayMode,
		&i.Interactive,
	)
	return i, err
}

const listAnnotationComments = `-- name: ListAnnotationComments :many
SELECT annotation_comments.annotation_id, annotation_comments.user_id, annotation_comments.body, annotation_comments.id, annotation_comments.created_at, annotation_comments.updated_at, users.username AS author_username
FROM annotation_comments
JOIN users ON users.id = annotation_comments.user_id
WHERE annotation_comments.annotation_id = $1
ORDER BY annotation_comments.created_at ASC
`

type ListAnnotationCommentsRow struct {
	AnnotationID   uuid.UUID        `json:"annotation_id"`
	UserID         uuid.UUID        `json:"user_id"`
	Body           string           `json:"body"`
	ID             uuid.UUID        `json:"id"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	AuthorUsername string           `json:"author_username"`
}

func (q *Queries) ListAnnotationComments(ctx context.Context, annotationID uuid.UUID) ([]ListAnnotationCommentsRow, error) {
	rows, err := q.db.Query(ctx, listAnnotationComments, annotationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnnotationCommentsRow{}
	for rows.Next() {
		var i ListAnnotationCommentsRow
		if err := rows.Scan(
			&i.AnnotationID,
			&i.UserID,
			&i.Body,
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnnotationsForVideo = `-- name: ListAnnotationsForVideo :many
SELECT video_id, timestamp_seconds, content, kind, color, custom_data, id, created_at, updated_at, duration_seconds, position_x, position_y, region_x, region_y, region_width, region_height, shape, display_mode, interactive FROM annotations
WHERE video_id = $1
ORDER BY timestamp_seconds ASC, created_at ASC
`

func (q *Queries) ListAnnotationsForVideo(ctx context.Context, videoID uuid.UUID) ([]Annotation, error) {
	rows, err := q.db.Query(ctx, listAnnotationsForVideo, videoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Annotation{}
	for rows.Next() {
		var i Annotation
		if err := rows.Scan(
			&i.VideoID,
			&i.TimestampSeconds,
			&i.Content,
			&i.Kind,
			&i.Color,
			&i.CustomData,
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DurationSeconds,
			&i.PositionX,
			&i.PositionY,
			&i.RegionX,
			&i.RegionY,
			&i.RegionWidth,
			&i.RegionHeight,
			&i.Shape,
			&i.DisplayMode,
			&i.Interactive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnnotation = `-- name: UpdateAnnotation :one
UPDATE annotations SET
    timestamp_seconds = $2,
    duration_seconds = $3,
    position_x = $4,
    position_y = $5,
    region_x = $6,
    region_y = $7,
    region_width = $8,
    region_height = $9,
    shape = $10,
    display_mode = $11,
    interactive = $12,
    content = $13,
    kind = $14,
    color = $15,
    custom_data = $16,
    updated_at = now()
WHERE id = $1
RETURNING video_id, timestamp_seconds, content, kind, color, custom_data, id, created_at, updated_at, duration_seconds, position_x, position_y, region_x, region_y, region_width, region_height, shape, display_mode, interactive
`

type UpdateAnnotationParams struct {
	ID               uuid.UUID `json:"id"`
	TimestampSeconds float64   `json:"timestamp_seconds"`
	DurationSeconds  float64   `json:"duration_seconds"`
	PositionX        *float64  `json:"position_x"`
	PositionY        *float64  `json:"position_y"`
	RegionX          *float64  `json:"region_x"`
	RegionY          *float64  `json:"region_y"`
	RegionWidth      *float64  `json:"region_width"`
	RegionHeight     *float64  `json:"region_height"`
	Shape            string    `json:"shape"`
	DisplayMode      string    `json:"display_mode"`
	Interactive      bool      `json:"interactive"`
	Content          []byte    `json:"content"`
	Kind             string    `json:"kind"`
	Color            string    `json:"color"`
	CustomData       []byte    `json:"custom_data"`
}

func (q *Queries) UpdateAnnotation(ctx context.Context, arg UpdateAnnotationParams) (Annotation, error) {
	row := q.db.QueryRow(ctx, updateAnnotation,
		arg.ID,
		arg.TimestampSeconds,
		arg.DurationSeconds,
		arg.PositionX,
		arg.PositionY,
		arg.RegionX,
		arg.RegionY,
		arg.RegionWidth,
		arg.RegionHeight,
		arg.Shape,
		arg.DisplayMode,
		arg.Interactive,
		arg.Content,
		arg.Kind,
		arg.Color,
		arg.CustomData,
	)
	var i Annotation
	err := row.Scan(
		&i.VideoID,
		&i.TimestampSeconds,
		&i.Content,
		&i.Kind,
		&i.Color,
		&i.CustomData,
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DurationSeconds,
		&i.PositionX,
		&i.PositionY,
		&i.RegionX,
		&i.RegionY,
		&i.RegionWidth,
		&i.RegionHeight,
		&i.Shape,
		&i.DisplayMode,
		&i.Interactive,
	)
	return i, err
}
