// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: drive_exports.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimDriveExport = `-- name: ClaimDriveExport :one
WITH candidate AS (
    SELECT id
    FROM drive_exports
    WHERE
        (status = 'pending' AND available_at <= now())
        OR (
            status IN ('preparing', 'uploading')
            AND started_at < now() - interval '12 hours'
        )
    ORDER BY available_at ASC, created_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE drive_exports
SET
    status = 'preparing',
    error = NULL,
    attempts = attempts + 1,
    started_at = now(),
    updated_at = now()
WHERE id = (SELECT id FROM candidate)
RETURNING video_id, group_id, requested_by, status, destination_path, size_bytes, error, attempts, started_at, available_at, completed_at, id, created_at, updated_at
`

func (q *Queries) ClaimDriveExport(ctx context.Context) (DriveExport, error) {
	row := q.db.QueryRow(ctx, claimDriveExport)
	var i DriveExport
	err := row.Scan(
		&i.VideoID,
		&i.GroupID,
		&i.RequestedBy,
		&i.Status,
		&i.DestinationPath,
		&i.SizeBytes,
		&i.Error,
		&i.Attempts,
		&i.StartedAt,
		&i.AvailableAt,
		&i.CompletedAt,
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDriveExportByVideoForGroup = `-- name: GetDriveExportByVideoForGroup :one
SELECT video_id, group_id, requested_by, status, destination_path, size_bytes, error, attempts, started_at, available_at, completed_at, id, created_at, updated_at FROM drive_exports WHERE video_id = $1 AND group_id = $2
`

type GetDriveExportByVideoForGroupParams struct {
	VideoID uuid.UUID `json:"video_id"`
	GroupID uuid.UUID `json:"group_id"`
}

func (q *Queries) GetDriveExportByVideoForGroup(ctx context.Context, arg GetDriveExportByVideoForGroupParams) (DriveExport, error) {
	row := q.db.QueryRow(ctx, getDriveExportByVideoForGroup, arg.VideoID, arg.GroupID)
	var i DriveExport
	err := row.Scan(
		&i.VideoID,
		&i.GroupID,
		&i.RequestedBy,
		&i.Status,
		&i.DestinationPath,
		&i.SizeBytes,
		&i.Error,
		&i.Attempts,
		&i.StartedAt,
		&i.AvailableAt,
		&i.CompletedAt,
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markDriveExportCompleted = `-- name: MarkDriveExportCompleted :execrows
UPDATE drive_exports
SET
    status = 'completed',
    error = NULL,
    started_at = NULL,
    completed_at = now(),
    updated_at = now()
WHERE id = $1 AND status = 'uploading'
`

func (q *Queries) MarkDriveExportCompleted(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markDriveExportCompleted, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markDriveExportFailed = `-- name: MarkDriveExportFailed :execrows
UPDATE drive_exports
SET
    status = $2,
    error = $3,
    started_at = NULL,
    available_at = $4,
    updated_at = now()
WHERE id = $1 AND status IN ('preparing', 'uploading')
`

type MarkDriveExportFailedParams struct {
	ID          uuid.UUID        `json:"id"`
	Status      string           `json:"status"`
	Error       *string          `json:"error"`
	AvailableAt pgtype.Timestamp `json:"available_at"`
}

func (q *Queries) MarkDriveExportFailed(ctx context.Context, arg MarkDriveExportFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDriveExportFailed,
		arg.ID,
		arg.Status,
		arg.Error,
		arg.AvailableAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markDriveExportUploading = `-- name: MarkDriveExportUploading :execrows
UPDATE drive_exports
SET status = 'uploading', size_bytes = $2, updated_at = now()
WHERE id = $1 AND status = 'preparing'
`

type MarkDriveExportUploadingParams struct {
	ID        uuid.UUID `json:"id"`
	SizeBytes *int64    `json:"size_bytes"`
}

func (q *Queries) MarkDriveExportUploading(ctx context.Context, arg MarkDriveExportUploadingParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDriveExportUploading, arg.ID, arg.SizeBytes)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const queueDriveExport = `-- name: QueueDriveExport :one
INSERT INTO drive_exports (
    video_id, group_id, requested_by, status, destination_path
) VALUES ($1, $2, $3, 'pending', $4)
ON CONFLICT (video_id) DO UPDATE SET
    group_id = EXCLUDED.group_id,
    requested_by = EXCLUDED.requested_by,
    status = 'pending',
    destination_path = EXCLUDED.destination_path,
    size_bytes = NULL,
    error = NULL,
    attempts = 0,
    started_at = NULL,
    available_at = now(),
    completed_at = NULL,
    updated_at = now()
RETURNING video_id, group_id, requested_by, status, destination_path, size_bytes, error, attempts, started_at, available_at, completed_at, id, created_at, updated_at
`

type QueueDriveExportParams struct {
	VideoID         uuid.UUID `json:"video_id"`
	GroupID         uuid.UUID `json:"group_id"`
	RequestedBy     uuid.UUID `json:"requested_by"`
	DestinationPath string    `json:"destination_path"`
}

func (q *Queries) QueueDriveExport(ctx context.Context, arg QueueDriveExportParams) (DriveExport, error) {
	row := q.db.QueryRow(ctx, queueDriveExport,
		arg.VideoID,
		arg.GroupID,
		arg.RequestedBy,
		arg.DestinationPath,
	)
	var i DriveExport
	err := row.Scan(
		&i.VideoID,
		&i.GroupID,
		&i.RequestedBy,
		&i.Status,
		&i.DestinationPath,
		&i.SizeBytes,
		&i.Error,
		&i.Attempts,
		&i.StartedAt,
		&i.AvailableAt,
		&i.CompletedAt,
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const requeueInterruptedDriveExports = `-- name: RequeueInterruptedDriveExports :execrows
UPDATE drive_exports
SET
    status = 'pending',
    started_at = NULL,
    available_at = now(),
    updated_at = now()
WHERE status IN ('preparing', 'uploading')
`

func (q *Queries) RequeueInterruptedDriveExports(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, requeueInterruptedDriveExports)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
