// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Annotation struct {
	VideoID          uuid.UUID        `json:"video_id"`
	TimestampSeconds float64          `json:"timestamp_seconds"`
	Content          []byte           `json:"content"`
	Kind             string           `json:"kind"`
	Color            string           `json:"color"`
	CustomData       []byte           `json:"custom_data"`
	ID               uuid.UUID        `json:"id"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
	DurationSeconds  float64          `json:"duration_seconds"`
	PositionX        *float64         `json:"position_x"`
	PositionY        *float64         `json:"position_y"`
	RegionX          *float64         `json:"region_x"`
	RegionY          *float64         `json:"region_y"`
	RegionWidth      *float64         `json:"region_width"`
	RegionHeight     *float64         `json:"region_height"`
	Shape            string           `json:"shape"`
	DisplayMode      string           `json:"display_mode"`
	Interactive      bool             `json:"interactive"`
}

type AnnotationComment struct {
	AnnotationID uuid.UUID        `json:"annotation_id"`
	UserID       uuid.UUID        `json:"user_id"`
	Body         string           `json:"body"`
	ID           uuid.UUID        `json:"id"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type Group struct {
	Name      string           `json:"name"`
	ID        uuid.UUID        `json:"id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	Username     string           `json:"username"`
	PasswordHash string           `json:"password_hash"`
	ID           uuid.UUID        `json:"id"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	IsAdmin      bool             `json:"is_admin"`
	GroupID      uuid.UUID        `json:"group_id"`
}

type Video struct {
	Title                 string           `json:"title"`
	Description           *string          `json:"description"`
	ObjectKey             string           `json:"object_key"`
	OriginalFilename      string           `json:"original_filename"`
	ContentType           string           `json:"content_type"`
	SizeBytes             int64            `json:"size_bytes"`
	ProcessingStatus      string           `json:"processing_status"`
	ProcessingError       *string          `json:"processing_error"`
	ProcessingAttempts    int32            `json:"processing_attempts"`
	ProcessingStartedAt   pgtype.Timestamp `json:"processing_started_at"`
	ProcessingAvailableAt pgtype.Timestamp `json:"processing_available_at"`
	ID                    uuid.UUID        `json:"id"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
	GroupID               uuid.UUID        `json:"group_id"`
}
