// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountVideosForGroup(ctx context.Context, groupID uuid.UUID) (int64, error)
	CreateAnnotation(ctx context.Context, arg CreateAnnotationParams) (Annotation, error)
	CreateGroup(ctx context.Context, name string) (Group, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error)
	DeleteAnnotation(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteVideo(ctx context.Context, arg DeleteVideoParams) (int64, error)
	GetAnnotationByID(ctx context.Context, id uuid.UUID) (Annotation, error)
	GetGroupByID(ctx context.Context, id uuid.UUID) (Group, error)
	GetGroupByName(ctx context.Context, name string) (Group, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetVideoByIDForGroup(ctx context.Context, arg GetVideoByIDForGroupParams) (Video, error)
	ListAnnotationsForVideo(ctx context.Context, videoID uuid.UUID) ([]Annotation, error)
	ListGroups(ctx context.Context) ([]Group, error)
	ListVideosForGroup(ctx context.Context, arg ListVideosForGroupParams) ([]Video, error)
	UpdateAnnotation(ctx context.Context, arg UpdateAnnotationParams) (Annotation, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateVideo(ctx context.Context, arg UpdateVideoParams) (Video, error)
}

var _ Querier = (*Queries)(nil)
