// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: videos.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimVideoForProcessing = `-- name: ClaimVideoForProcessing :one
WITH candidate AS (
    SELECT id
    FROM videos
    WHERE
        (processing_status = 'pending' AND processing_available_at <= now())
        OR (
            processing_status = 'processing'
            AND processing_started_at < now() - interval '6 hours'
        )
    ORDER BY processing_available_at ASC, created_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE videos
SET
    processing_status = 'processing',
    processing_error = NULL,
    processing_attempts = processing_attempts + 1,
    processing_started_at = now(),
    updated_at = now()
WHERE id = (SELECT id FROM candidate)
RETURNING title, description, object_key, original_filename, content_type, size_bytes, processing_status, processing_error, processing_attempts, processing_started_at, processing_available_at, id, created_at, updated_at, group_id
`

func (q *Queries) ClaimVideoForProcessing(ctx context.Context) (Video, error) {
	row := q.db.QueryRow(ctx, claimVideoForProcessing)
	var i Video
	err := row.Scan(
		&i.Title,
		&i.Description,
		&i.ObjectKey,
		&i.OriginalFilename,
		&i.ContentType,
		&i.SizeBytes,
		&i.ProcessingStatus,
		&i.ProcessingError,
		&i.ProcessingAttempts,
		&i.ProcessingStartedAt,
		&i.ProcessingAvailableAt,
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
	)
	return i, err
}

const countVideosForGroup = `-- name: CountVideosForGroup :one
SELECT count(*) FROM videos WHERE group_id = $1
`

func (q *Queries) CountVideosForGroup(ctx context.Context, groupID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVideosForGroup, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (
    group_id, title, description, object_key, original_filename, content_type, size_bytes,
    processing_status
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING title, description, object_key, original_filename, content_type, size_bytes, processing_status, processing_error, processing_attempts, processing_started_at, processing_available_at, id, created_at, updated_at, group_id
`

type CreateVideoParams struct {
	GroupID          uuid.UUID `json:"group_id"`
	Title            string    `json:"title"`
	Description      *string   `json:"description"`
	ObjectKey        string    `json:"object_key"`
	OriginalFilename string    `json:"original_filename"`
	ContentType      string    `json:"content_type"`
	SizeBytes        int64     `json:"size_bytes"`
	ProcessingStatus string    `json:"processing_status"`
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, createVideo,
		arg.GroupID,
		arg.Title,
		arg.Description,
		arg.ObjectKey,
		arg.OriginalFilename,
		arg.ContentType,
		arg.SizeBytes,
		arg.ProcessingStatus,
	)
	var i Video
	err := row.Scan(
		&i.Title,
		&i.Description,
		&i.ObjectKey,
		&i.OriginalFilename,
		&i.ContentType,
		&i.SizeBytes,
		&i.ProcessingStatus,
		&i.ProcessingError,
		&i.ProcessingAttempts,
		&i.ProcessingStartedAt,
		&i.ProcessingAvailableAt,
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
	)
	return i, err
}

const deleteVideo = `-- name: DeleteVideo :execrows
DELETE FROM videos
WHERE id = $1 AND group_id = $2 AND processing_status <> 'processing'
`

type DeleteVideoParams struct {
	ID      uuid.UUID `json:"id"`
	GroupID uuid.UUID `json:"group_id"`
}

func (q *Queries) DeleteVideo(ctx context.Context, arg DeleteVideoParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVideo, arg.ID, arg.GroupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getVideoByIDForGroup = `-- name: GetVideoByIDForGroup :one
SELECT title, description, object_key, original_filename, content_type, size_bytes, processing_status, processing_error, processing_attempts, processing_started_at, processing_available_at, id, created_at, updated_at, group_id FROM videos WHERE id = $1 AND group_id = $2
`

type GetVideoByIDForGroupParams struct {
	ID      uuid.UUID `json:"id"`
	GroupID uuid.UUID `json:"group_id"`
}

func (q *Queries) GetVideoByIDForGroup(ctx context.Context, arg GetVideoByIDForGroupParams) (Video, error) {
	row := q.db.QueryRow(ctx, getVideoByIDForGroup, arg.ID, arg.GroupID)
	var i Video
	err := row.Scan(
		&i.Title,
		&i.Description,
		&i.ObjectKey,
		&i.OriginalFilename,
		&i.ContentType,
		&i.SizeBytes,
		&i.ProcessingStatus,
		&i.ProcessingError,
		&i.ProcessingAttempts,
		&i.ProcessingStartedAt,
		&i.ProcessingAvailableAt,
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
	)
	return i, err
}

const listVideosForGroup = `-- name: ListVideosForGroup :many
SELECT title, description, object_key, original_filename, content_type, size_bytes, processing_status, processing_error, processing_attempts, processing_started_at, processing_available_at, id, created_at, updated_at, group_id FROM videos
WHERE group_id = $1
ORDER BY created_at DESC
OFFSET $2 LIMIT $3
`

type ListVideosForGroupParams struct {
	GroupID uuid.UUID `json:"group_id"`
	Offset  int32     `json:"offset"`
	Limit   int32     `json:"limit"`
}

func (q *Queries) ListVideosForGroup(ctx context.Context, arg ListVideosForGroupParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, listVideosForGroup, arg.GroupID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.Title,
			&i.Description,
			&i.ObjectKey,
			&i.OriginalFilename,
			&i.ContentType,
			&i.SizeBytes,
			&i.ProcessingStatus,
			&i.ProcessingError,
			&i.ProcessingAttempts,
			&i.ProcessingStartedAt,
			&i.ProcessingAvailableAt,
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markVideoProcessingFailed = `-- name: MarkVideoProcessingFailed :execrows
UPDATE videos
SET
    processing_status = $2,
    processing_error = $3,
    processing_started_at = NULL,
    processing_available_at = $4,
    updated_at = now()
WHERE id = $1 AND processing_status = 'processing'
`

type MarkVideoProcessingFailedParams struct {
	ID                    uuid.UUID        `json:"id"`
	ProcessingStatus      string           `json:"processing_status"`
	ProcessingError       *string          `json:"processing_error"`
	ProcessingAvailableAt pgtype.Timestamp `json:"processing_available_at"`
}

func (q *Queries) MarkVideoProcessingFailed(ctx context.Context, arg MarkVideoProcessingFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markVideoProcessingFailed,
		arg.ID,
		arg.ProcessingStatus,
		arg.ProcessingError,
		arg.ProcessingAvailableAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markVideoProcessingReady = `-- name: MarkVideoProcessingReady :execrows
UPDATE videos
SET
    processing_status = 'ready',
    processing_error = NULL,
    processing_started_at = NULL,
    size_bytes = $2,
    updated_at = now()
WHERE id = $1 AND processing_status = 'processing'
`

type MarkVideoProcessingReadyParams struct {
	ID        uuid.UUID `json:"id"`
	SizeBytes int64     `json:"size_bytes"`
}

func (q *Queries) MarkVideoProcessingReady(ctx context.Context, arg MarkVideoProcessingReadyParams) (int64, error) {
	result, err := q.db.Exec(ctx, markVideoProcessingReady, arg.ID, arg.SizeBytes)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requeueInterruptedVideoProcessing = `-- name: RequeueInterruptedVideoProcessing :execrows
UPDATE videos
SET
    processing_status = 'pending',
    processing_started_at = NULL,
    processing_available_at = now(),
    updated_at = now()
WHERE processing_status = 'processing'
`

func (q *Queries) RequeueInterruptedVideoProcessing(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, requeueInterruptedVideoProcessing)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateVideo = `-- name: UpdateVideo :one
UPDATE videos
SET title = $3, description = $4, updated_at = now()
WHERE id = $1 AND group_id = $2
RETURNING title, description, object_key, original_filename, content_type, size_bytes, processing_status, processing_error, processing_attempts, processing_started_at, processing_available_at, id, created_at, updated_at, group_id
`

type UpdateVideoParams struct {
	ID          uuid.UUID `json:"id"`
	GroupID     uuid.UUID `json:"group_id"`
	Title       string    `json:"title"`
	Description *string   `json:"description"`
}

func (q *Queries) UpdateVideo(ctx context.Context, arg UpdateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, updateVideo,
		arg.ID,
		arg.GroupID,
		arg.Title,
		arg.Description,
	)
	var i Video
	err := row.Scan(
		&i.Title,
		&i.Description,
		&i.ObjectKey,
		&i.OriginalFilename,
		&i.ContentType,
		&i.SizeBytes,
		&i.ProcessingStatus,
		&i.ProcessingError,
		&i.ProcessingAttempts,
		&i.ProcessingStartedAt,
		&i.ProcessingAvailableAt,
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
	)
	return i, err
}
