"""add annotation preview fields

Revision ID: a9a50ffd3ced
Revises: 202606220001
Create Date: 2026-06-22 19:32:59.291223
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "a9a50ffd3ced"
down_revision: str | None = "202606220001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "annotations",
        sa.Column("duration_seconds", sa.Float(), server_default="6.0", nullable=False),
    )
    op.add_column("annotations", sa.Column("position_x", sa.Float(), nullable=True))
    op.add_column("annotations", sa.Column("position_y", sa.Float(), nullable=True))
    op.add_column("annotations", sa.Column("region_x", sa.Float(), nullable=True))
    op.add_column("annotations", sa.Column("region_y", sa.Float(), nullable=True))
    op.add_column("annotations", sa.Column("region_width", sa.Float(), nullable=True))
    op.add_column("annotations", sa.Column("region_height", sa.Float(), nullable=True))
    op.add_column(
        "annotations",
        sa.Column("shape", sa.String(), server_default="marker", nullable=False),
    )
    op.add_column(
        "annotations",
        sa.Column("display_mode", sa.String(), server_default="card", nullable=False),
    )
    op.add_column(
        "annotations",
        sa.Column("interactive", sa.Boolean(), server_default=sa.true(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("annotations", "interactive")
    op.drop_column("annotations", "display_mode")
    op.drop_column("annotations", "shape")
    op.drop_column("annotations", "region_height")
    op.drop_column("annotations", "region_width")
    op.drop_column("annotations", "region_y")
    op.drop_column("annotations", "region_x")
    op.drop_column("annotations", "position_y")
    op.drop_column("annotations", "position_x")
    op.drop_column("annotations", "duration_seconds")
    # ### end Alembic commands ###
