[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
axum = { version = "0.8", features = ["ws"] }
clap = { version = "4", features = ["derive"] }
futures-util = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tokio = { version = "1", features = ["full"] }
tokio-serial = "5.4"
makepad-widgets = { git = "https://github.com/makepad/makepad.git", rev = "152b11f20a8cf8e81bfd0086210cb9b0269c51e9", version = "2.0.0" }
robius-file-picker = "0.3"
